os:
  - osx

osx_image: xcode9.3

language: java

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native/
    - $HOME/.gradle/daemon/native/

env:
  global:
    secure: "AvNOCxZ5/QThkyHeh+txThK29tLC66goQfpSv1BGCgcrpaLx5ZlGaCQJ+JRIunewg/uZwY3Yl6dWX1ggNnGysySX2dXDObNAvxYqG8UCA8nu/qYEUlWMAc7JxhGZDBOJzNZSVZJ8aL2egMl4P1ZISDMH3HkKcMUcoFNxocTrZeDhCFZW2nwqes62RfsAmntKn2uDSxvEIe65CQ5TOpC2MZyM7f6d3ZVE5/5i6f3XfP5jX0SvloL0WxzueSYCMohAiX04iDY46mXCLcPvDR1A5cykh8egHkAOIHYU3xUcug5/1wIJJZoKX6R7ApM4cRBUsBsxaedL4/ZTZn6LeIoUKi1ioW82A0X5VAZ47y8uQXb6P79pj5i4j4lNK5McyO97rLPEt1RLqFsVlKSaSDq4gDXAwiUDwwV+aFMOE1HTwzXfqjXdVq51btgRr1Qbi7ZyZPdcZT4aHY/lbP/SL31AJgK57+xKoa//ubWl9Xl1LNMS1+cGgKO5/UmbxScB87ql3fLIifDpgSZNa5HwItI6C3gG/kSnAjaWcU6hI8P0kTnJAfLn4vAlfrBs6rb4orCA6qunSVOSOQCVzWoHSLd8S6l6YElnXxzb4GzmfphluLuBdBNqIxeLKaK3UWwLe41mwn5ugWmDn3JY1oEWJP1vRmiq0WAc7Fd1fjuCaqkK0sE="
    secure: "PvT/zPTqzBN0rvLwN6ISSVSTQjU8Hk0i3wwshKR2j0pL6zosukB9NSpYGsmEF5l7acEXiBq5QJjCRCgoGbEyXumIonxcSHvtXgN2aQwBKUHO5hBww6e3kHYpkqVRYQHvLaZP5pLs7XvQwpGrgKkqHGZ6FZRGTteNY+O5Pq4Vu1YHmVGgn5DZf1biPC+53IkVvqvLFUAACb+33to8S9loKZ1IQHDIpWleN4qv2AvgQasdPZQ0kLeifKLes1W13PzYS9gdMmHr5jyaE5iRrUe79yIwTJ+PCpN//Mjm065hveB5UVYP+L0CTQweVqa/YOH1+HuIDejJOmdWF0JY2bvaEQP7zEXfEOtK9YZyDW91k136Te5ZCasYPpl50HRhNWiSns/ycc5oQrIX1P6Ebh9+mvH5tK/Bih65L+EkcuiL5MN2q26ywJGCgORHvoTcXXIPqOmLQypUjs1DGjJCP7IaxG2Q9aLI8uY9vToKh4QURgw8Vu3jJJl7de6NH4BAFBepx5NNfOaVV0rqKErhXgyoEFtOI0Jm4S+d+yP9A9y156197kP0ZC9nTKqC3839buOWuo03bhEvv5qCtkeZiTgIMkHXnFezfMsg3wVLZ0Ts+JBJjtNOeg3ssM4ZLR4l8pPcZi5ChbdxGpJiGajDSu7eeQbImsw2IOchGnjG1E5B7d8="
